// <auto-generated />
using System;
using CLMS.CoursesContentManagement.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CLMS.CoursesContentManagement.Persistance.Migrations
{
    [DbContext(typeof(ContentContext))]
    [Migration("20190116000259_AddedOriginId")]
    partial class AddedOriginId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CLMS.CoursesContentManagement.Domain.Content", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ContentHolderId");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted");

                    b.HasKey("Id");

                    b.HasIndex("ContentHolderId");

                    b.ToTable("Content");
                });

            modelBuilder.Entity("CLMS.CoursesContentManagement.Domain.ContentHolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("HolderEmail");

                    b.Property<string>("Name");

                    b.Property<Guid>("OriginId");

                    b.HasKey("Id");

                    b.ToTable("ContentHolders");
                });

            modelBuilder.Entity("CLMS.CoursesContentManagement.Domain.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ContentId");

                    b.Property<string>("Extension");

                    b.Property<Guid>("FileContentId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("FileContentId")
                        .IsUnique();

                    b.ToTable("File");
                });

            modelBuilder.Entity("CLMS.CoursesContentManagement.Domain.FileContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Bytes");

                    b.HasKey("Id");

                    b.ToTable("FileContent");
                });

            modelBuilder.Entity("CLMS.CoursesContentManagement.Domain.Content", b =>
                {
                    b.HasOne("CLMS.CoursesContentManagement.Domain.ContentHolder")
                        .WithMany("Contents")
                        .HasForeignKey("ContentHolderId");
                });

            modelBuilder.Entity("CLMS.CoursesContentManagement.Domain.File", b =>
                {
                    b.HasOne("CLMS.CoursesContentManagement.Domain.Content")
                        .WithMany("Files")
                        .HasForeignKey("ContentId");

                    b.HasOne("CLMS.CoursesContentManagement.Domain.FileContent", "Content")
                        .WithOne()
                        .HasForeignKey("CLMS.CoursesContentManagement.Domain.File", "FileContentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
